name: custom_bottom_navigation
description: A Custom bottom navigation bar with box animation. This is the simplified and smoother version of some of the earlier designs. You can use it just as a regular material bottom navigation bar, but with more customization and animation.
version: 0.0.1+1
homepage: https://github.com/shivamsoni1501/custom_bottom_navigation

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
